- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: sample-key
      ec2_key:
        name: sample-key
        region: us-east-2
      register: keyout

    - debug:
        var: keyout

    - name: copy-key
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./sample-key.pem
      when: keyout.changed

