- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: IMPORT VPC VARIABLES
      include_vars: vars/vpc_setup
    
    - name: CREATE VPROFILE VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout
    
    - debug:
        var: vpcout 
    
    - name: CREATE PUBLIC SUBNET 1 IN ZONE 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{PubSub1Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsub1out

    - name: CREATE PUBLIC SUBNET 2 IN ZONE 2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{PubSub2Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub2
      register: pubsub2out
    
    - name: CREATE PUBLIC SUBNET 3 IN ZONE 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        cidr: "{{PubSub3Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub3
      register: pubsub3out

    - name: CREATE PUBLIC SUBNET 4 IN ZONE 4
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone4}}"
        state: "{{state}}"
        cidr: "{{PubSub4Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub4
      register: pubsub4out

    - name: CREATE PUBLIC SUBNET 5 IN ZONE 5
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone5}}"
        state: "{{state}}"
        cidr: "{{PubSub5Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub5
      register: pubsub5out

    - name: CREATE PUBLIC SUBNET 6 IN ZONE 6
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone6}}"
        state: "{{state}}"
        cidr: "{{PubSub6Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub6
      register: pubsub6out