#!/bin/bash
TARGET="/home/devmarinamenezes/public_html"
GIT_DIR="/home/devmarinamenezes/devbertholdo/marinamenezes.git"
BRANCH="master"

while read oldrev newrev ref
do
        # apenas verificando se o branch e o master.
        if [ "$ref" = "refs/heads/$BRANCH" ];
        then
                echo "Ref $ref recebido. Realizando deploy no branch ${BRANCH} para https://devmarinamenezes.brtloja.com.br/"
                git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
                echo "Permissões atualizadas!"
                echo "Deploy realizado com sucesso!"
        else
                echo "Ref $ref recebido. Deploy negado: somente o ramo $ {BRANCH} pode ser implantado neste servidor."
        fi
done
